<%@ Page Title="Delete Overtime" Language="C#" MasterPageFile="~/ManagerMaster.Master" AutoEventWireup="true" CodeBehind="ManageOvertime.aspx.cs" Inherits="SignMeUp.ManageOvertime" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
<h2> Delete Overtime</h2><br />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" DataKeyNames="OvertimeID" DataSourceID="SqlDataSource1" AllowSorting="True"  GridLines="None" ShowHeader="False">
        <Columns>
                 <asp:TemplateField>
                    <ItemTemplate>

                        <table class="table table-hover"style="border: 1px solid grey; margin:20px; padding:5px; background-color: white">
                            <tr>
                                <td style="width: 200px;">
                                   <asp:Image ID="imgOvertime" ImageURL='<%# Eval("PhotoPath") %>' runat="server" />

                                </td>
                                <td style="width: 200px">
                                    <table>
                                        <tr>
                                            <td>
                                                <b>Location:</b>
                                            </td>
                                            <td>
                                                <asp:Label ID="lblLocation" runat="server" Text='<%#Eval("Location") %>'></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <b>Overtime Date:</b>
                                            </td>
                                            <td>
                                                <asp:Label ID="lblOvertimeDate" runat="server" Text='<%#Eval("OvertimeDate") %>'></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <b> Start Time: </b>
                                            </td>
                                            <td>
                                                <asp:Label ID="lblStartTime" runat="server" Text='<%#Eval("HoursBegin") %>'></asp:Label>
                                            </td>
                                            <tr>
                                                <td>
                                                    <b>End Time: </b>
                                                </td>
                                                <td>
                                                    <asp:Label ID="Label1" runat="server" Text='<%#Eval("HoursEnd") %>'></asp:Label>
                                                </td>
                                            </tr>
                                        <tr>
                                            <td>
                                                <b>Deadline to apply: </b>
                                            </td>
                                            <td>
                                                <asp:Label ID="Label2" runat="server" Text='<%#Eval("Deadline") %>'></asp:Label><br />
                                                <asp:Button ID="btnHire" runat="server" Text="Hire someone!" />
                                                <div id="hirefield">

                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>

                        </table>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
    </asp:GridView>

    <asp:SqlDataSource ID="SqlDataSource1" runat="server"  ConnectionString="<%$ ConnectionStrings:SignMeUpLocalConnectionString %>" DeleteCommand="DELETE FROM [Overtime] WHERE [OvertimeID] = @original_OvertimeID" InsertCommand="INSERT INTO [Overtime] ([OvertimeDate], [HoursBegin], [HoursEnd], [Deadline], [Location], [StillAdvertise], [InterestedEmployees], [FilledYet], [PhotoPath]) VALUES (@OvertimeDate, @HoursBegin, @HoursEnd, @Deadline, @Location, @StillAdvertise, @InterestedEmployees, @FilledYet, @PhotoPath)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Overtime] ORDER BY [OvertimeDate]" UpdateCommand="UPDATE [Overtime] SET [OvertimeDate] = @OvertimeDate, [HoursBegin] = @HoursBegin, [HoursEnd] = @HoursEnd, [Deadline] = @Deadline, [Location] = @Location, [StillAdvertise] = @StillAdvertise, [InterestedEmployees] = @InterestedEmployees, [FilledYet] = @FilledYet, [PhotoPath] = @PhotoPath WHERE [OvertimeID] = @original_OvertimeID">
        <DeleteParameters>
            <asp:Parameter Name="original_OvertimeID" Type="Int32" />
            <asp:Parameter Name="original_OvertimeDate" Type="String" />
            <asp:Parameter Name="original_HoursBegin" Type="String" />
            <asp:Parameter Name="original_HoursEnd" Type="String" />
            <asp:Parameter Name="original_Deadline" Type="String" />
            <asp:Parameter Name="original_Location" Type="String" />
            <asp:Parameter Name="original_StillAdvertise" Type="Boolean" />
            <asp:Parameter Name="original_InterestedEmployees" Type="String" />
            <asp:Parameter Name="original_FilledYet" Type="Boolean" />
            <asp:Parameter Name="original_PhotoPath" Type="String" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="OvertimeDate" Type="String" />
            <asp:Parameter Name="HoursBegin" Type="String" />
            <asp:Parameter Name="HoursEnd" Type="String" />
            <asp:Parameter Name="Deadline" Type="String" />
            <asp:Parameter Name="Location" Type="String" />
            <asp:Parameter Name="StillAdvertise" Type="Boolean" />
            <asp:Parameter Name="InterestedEmployees" Type="String" />
            <asp:Parameter Name="FilledYet" Type="Boolean" />
            <asp:Parameter Name="PhotoPath" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="OvertimeDate" Type="String" />
            <asp:Parameter Name="HoursBegin" Type="String" />
            <asp:Parameter Name="HoursEnd" Type="String" />
            <asp:Parameter Name="Deadline" Type="String" />
            <asp:Parameter Name="Location" Type="String" />
            <asp:Parameter Name="StillAdvertise" Type="Boolean" />
            <asp:Parameter Name="InterestedEmployees" Type="String" />
            <asp:Parameter Name="FilledYet" Type="Boolean" />
            <asp:Parameter Name="PhotoPath" Type="String" />
            <asp:Parameter Name="original_OvertimeID" Type="Int32" />
            <asp:Parameter Name="original_OvertimeDate" Type="String" />
            <asp:Parameter Name="original_HoursBegin" Type="String" />
            <asp:Parameter Name="original_HoursEnd" Type="String" />
            <asp:Parameter Name="original_Deadline" Type="String" />
            <asp:Parameter Name="original_Location" Type="String" />
            <asp:Parameter Name="original_StillAdvertise" Type="Boolean" />
            <asp:Parameter Name="original_InterestedEmployees" Type="String" />
            <asp:Parameter Name="original_FilledYet" Type="Boolean" />
            <asp:Parameter Name="original_PhotoPath" Type="String" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <p>
    </p>

                <div id="bot-box">
                <p id="bot-bubble">
                Hello Management Team Member!<br />
                <br />
                Did you know? If you delete overtime here, it will disappear from the Current Opportunities page, but I won't send any emails notifying anyone of the cancelation of the opportunity, even if someone has already signed up! 
            </p>
            <img src="images/happyRobot.jpg" alt="Helper Bot" />
        </div>

    

</asp:Content>
